// apps/desktop/src/ToastArea.svelte
<script lang="ts">
  import { AlertCircle, AlertTriangle, CheckCircle, Info, X } from '@lucide/svelte';
  import type { ToastMessage } from './types';

  interface Props {
    toasts: ToastMessage[];
    onRemove: (id: string) => void;
  }

  let { toasts, onRemove }: Props = $props();

  const TOAST_AUTO_CLOSE_MS = 3000;

  $effect(() => {
    const timers = toasts
      .filter((toast) => toast.autoClose !== false)
      .map((toast) => window.setTimeout(() => onRemove(toast.id), TOAST_AUTO_CLOSE_MS));
    return () => timers.forEach((timer) => window.clearTimeout(timer));
  });

  function configFor(type: ToastMessage['type']) {
    if (type === 'success') return { icon: CheckCircle, iconClass: 'text-green-500', border: 'border-green-500/20' };
    if (type === 'warning') return { icon: AlertTriangle, iconClass: 'text-yellow-500', border: 'border-yellow-500/20' };
    if (type === 'error') return { icon: AlertCircle, iconClass: 'text-red-500', border: 'border-red-500/20' };
    return { icon: Info, iconClass: 'text-primary', border: 'border-primary/20' };
  }
</script>

{#if toasts.length > 0}
<div class="fixed bottom-20 right-6 z-50 flex w-full max-w-sm flex-col gap-3 pointer-events-none">
  {#each toasts as toast (toast.id)}
    {@const config = configFor(toast.type)}
    {@const Icon = config.icon}
    <article class={`pointer-events-auto flex items-start gap-4 rounded-md border bg-card p-4 shadow-lg animate-in slide-in-from-bottom-5 fade-in duration-300 ${config.border}`}>
      <div class="mt-0.5 shrink-0">
        <Icon size={20} class={config.iconClass} />
      </div>
      <div class="min-w-0 flex-1">
        <h4 class="mb-1 text-sm font-semibold leading-none text-foreground">{toast.title}</h4>
        <p class="break-words text-sm leading-snug text-muted-foreground">{toast.message}</p>
      </div>
      <button class="-mr-1 -mt-1 shrink-0 rounded-md p-1 text-muted-foreground transition-colors hover:bg-muted focus:outline-none focus:ring-2 focus:ring-primary" title="Dismiss" aria-label="Dismiss" onclick={() => onRemove(toast.id)}>
        <X size={16} />
      </button>
    </article>
  {/each}
</div>
{/if}

// apps/desktop/src/ToastArea.tsx
import React, { useEffect } from 'react';
import type { ToastMessage } from './types';
import { X, CheckCircle, AlertCircle, Info, AlertTriangle } from 'lucide-react';

const TOAST_AUTO_CLOSE_MS = 3000;

interface ToastAreaProps {
  toasts: ToastMessage[];
  onDismiss: (id: string) => void;
}

export function ToastArea({ toasts, onDismiss }: ToastAreaProps) {
  if (toasts.length === 0) return null;

  return (
    <div className="fixed bottom-20 right-6 z-50 flex flex-col gap-3 w-full max-w-sm pointer-events-none">
      {toasts.map((toast) => (
        <ToastItem key={toast.id} toast={toast} onDismiss={onDismiss} />
      ))}
    </div>
  );
}

function ToastItem({ toast, onDismiss }: { toast: ToastMessage, onDismiss: (id: string) => void }) {
  useEffect(() => {
    if (toast.autoClose !== false) {
      const timer = setTimeout(() => onDismiss(toast.id), TOAST_AUTO_CLOSE_MS);
      return () => clearTimeout(timer);
    }
  }, [toast.id, toast.autoClose, onDismiss]);

  const typeConfig = {
    success: { icon: <CheckCircle size={20} className="text-green-500" />, border: 'border-green-500/20' },
    error: { icon: <AlertCircle size={20} className="text-red-500" />, border: 'border-red-500/20' },
    warning: { icon: <AlertTriangle size={20} className="text-yellow-500" />, border: 'border-yellow-500/20' },
    info: { icon: <Info size={20} className="text-primary" />, border: 'border-primary/20' },
  };

  const config = typeConfig[toast.type as keyof typeof typeConfig] || typeConfig.info;

  return (
    <div className={`pointer-events-auto flex items-start gap-4 p-4 bg-card border ${config.border} rounded-md shadow-lg animate-in slide-in-from-bottom-5 fade-in duration-300`}>
      <div className="flex-shrink-0 mt-0.5">
        {config.icon}
      </div>
      <div className="flex-1 min-w-0">
        <h4 className="text-sm font-semibold text-foreground mb-1 leading-none">{toast.title}</h4>
        <p className="text-sm text-muted-foreground leading-snug break-words">{toast.message}</p>
      </div>
      <button 
        onClick={() => onDismiss(toast.id)} 
        className="flex-shrink-0 p-1 -mt-1 -mr-1 rounded-md text-muted-foreground hover:bg-muted transition-colors focus:outline-none focus:ring-2 focus:ring-primary"
      >
        <X size={16} />
      </button>
    </div>
  );
}
